CREATE TABLE [dbo].[DB_CHANNEL]
(
	[CHANNEL_ID] NVARCHAR(50) NOT NULL,
	[TEAM_ID] NVARCHAR(50) NOT NULL,
	[CHANNEL_NAME] NVARCHAR(50) NULL,

	CONSTRAINT [PK_DB_CHANNEL] PRIMARY KEY ([CHANNEL_ID], [TEAM_ID])
)