CREATE TABLE [dbo].[DB_PULL]
(
	[PULL_ID] BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SEQ_PULL_ID, 
    [CALLER_NAME] NVARCHAR(50) NULL, 
    [PULLED_NAME] NVARCHAR(50) NULL, 
    [TEAM_ID] NVARCHAR(50) NULL, 
    [CHANNEL_ID] NVARCHAR(50) NULL, 
    [PULL_MESSAGE] NVARCHAR(MAX) NULL, 
    [PULL_DT] DATETIME2 NULL
)
